"""ADVS - ROI-targeted field recognition: RapidOCR detector + TrOCR recognizer.

Augments (does not replace) Tesseract's Stage-2 field extraction in
ocr_dryrun.py. Tesseract's own recognition accuracy is the reported problem,
not its layout detection or the template/field-mapping architecture, so this
module only recognizes field VALUES more accurately, using calibrated
per-template ROI zones (python/api/ocr_roi_config.json, generated by
generate_roi_config.py from the project's existing hand-calibrated field
boxes) instead of depending on correctly reading a field's caption label.

Pipeline, once per page:
    1. RapidOCR (PP-OCRv4 detector, detection-only: use_cls=False,
       use_rec=False) finds every text box on the page - cheap, ~8MB model.
    2. Each template field's ROI (a fraction of page width/height) is
       intersected against those boxes; detected boxes with >= 50% of their
       own area inside the ROI are unioned into one tight crop for that
       field. This crops to the ACTUAL text pixels rather than a fixed
       rectangle, and only needs the field's geometry - it does not depend
       on Tesseract (or anything else) having correctly read a caption label.
    3. The matched fields are GATED (select_fields_for_recognition): a field
       Tesseract already read confidently is skipped, because each crop costs
       ~10-30s of CPU inference and TrOCR is here to fix recognition failures,
       not redo successes. Required fields go first.
    4. Each surviving crop is recognized by TrOCR (microsoft/trocr-*-printed),
       until the caller's per-page time budget runs out.
    5. If the template's FIELD_SPECS defines a plain `regex` for that key,
       the recognized text must match it (group 1, or the whole match) - a
       lightweight validation reusing the codebase's own field formats
       without duplicating ocr_dryrun.py's fuller label/custom-parser logic.
    6. A field with no detected box, one the gate skipped, one the budget
       refused, or one whose TrOCR text fails validation, is simply absent
       from the returned dict - the caller (ocr.py) keeps today's
       label+regex+positional result for that field. Fail-forward, per-field,
       never raises.

Why the gate and the budget exist: ungated, a BIR page (13 ROI fields) took a
measured 409s against Laravel's 180s ML_API_TIMEOUT, which failed the whole
/v1/validate call and left Stage 2 AND Stage 3 blank in the officer
drill-down. The pass has to be bounded to be useful at all.

Business-permit ROI coverage spans all 5 synthesized city layouts (Digos,
Makati, Manila, Marikina, Taguig) via generate_roi_config.py's per-city
KEY_MAP, but not every field on every city's layout - a city whose form has
no honest match for a given BUSINESS_PERMIT_FIELD_SPECS key (e.g. Makati has
no distinct proprietor-name box; Manila's only date box is the OR/payment
date, not the issue date) simply has no ROI entry for that one field, and it
falls back to the existing label+regex extraction same as any other
unmatched field. A city not present in the config at all (a future new LGU
layout) returns {} entirely, same fallback.
"""
from __future__ import annotations

import re
import time
from typing import Any, Callable, NamedTuple

Box = tuple[float, float, float, float]  # (x, y, w, h) in pixel space


class RoiOutcome(NamedTuple):
    """``fields`` is what the caller merges (field key -> recognized value);
    ``diagnostics`` makes a slow or budget-truncated page observable instead
    of silent - which field crops were attempted, which produced a validated
    value, which the budget refused, and how long the pass actually took."""

    fields: dict[str, str]
    diagnostics: dict[str, Any]


def load_detector() -> Any:
    """RapidOCR ships its own PP-OCRv4 detector ONNX weights inside the pip
    package (no separate download/bake step needed)."""
    from rapidocr_onnxruntime import RapidOCR

    return RapidOCR()


def is_onnx_export(model_path: Any) -> bool:
    """True when ``model_path`` holds an ONNX export rather than a torch
    snapshot. The two layouts sit side by side under models/ and load through
    entirely different runtimes, and the caller only has the directory to go
    on. Quantization renames the graphs (``encoder_model_quantized.onnx``), so
    match the prefix, not an exact filename."""
    from pathlib import Path

    path = Path(model_path)
    return path.is_dir() and any(path.glob("encoder_model*.onnx"))


def load_trocr(model_path: Any) -> tuple[Any, Any]:
    """CPU-only; caller (ModelRegistry) is the load-once singleton.

    Returns ``(processor, model)`` for either layout — ``ORTModelForVision2Seq``
    exposes the same ``generate()`` surface as ``VisionEncoderDecoderModel``,
    so ``recognize_crop`` never learns which runtime it got.
    """
    from transformers import TrOCRProcessor

    processor = TrOCRProcessor.from_pretrained(model_path)

    if is_onnx_export(model_path):
        from optimum.onnxruntime import ORTModelForVision2Seq

        return processor, ORTModelForVision2Seq.from_pretrained(model_path)

    from transformers import VisionEncoderDecoderModel

    model = VisionEncoderDecoderModel.from_pretrained(model_path)
    model.eval()
    return processor, model


def detect_boxes(image, detector: Any) -> list[Box]:
    """Detection-only pass; returns axis-aligned (x, y, w, h) pixel boxes.

    ``image`` is whatever ocr_dryrun.preprocess() produces (a BGR/grayscale
    numpy array) - RapidOCR accepts numpy arrays directly, no PIL round-trip
    needed for detection.
    """
    result, _ = detector(image, use_cls=False, use_rec=False)
    boxes: list[Box] = []
    if not result:
        return boxes
    for polygon in result:
        xs = [point[0] for point in polygon]
        ys = [point[1] for point in polygon]
        x1, y1, x2, y2 = min(xs), min(ys), max(xs), max(ys)
        boxes.append((x1, y1, x2 - x1, y2 - y1))
    return boxes


def match_rois(
    boxes: list[Box],
    roi_config: dict[str, dict[str, float]],
    image_size: tuple[int, int],
    overlap_threshold: float = 0.5,
) -> dict[str, Box]:
    """For each field's fractional ROI, union every detected box that has
    >= overlap_threshold of its own area inside the ROI. Returns only fields
    with at least one match."""
    width, height = image_size
    matched: dict[str, Box] = {}
    for field, roi in roi_config.items():
        rx1 = roi["x"] * width
        ry1 = roi["y"] * height
        rx2 = rx1 + roi["w"] * width
        ry2 = ry1 + roi["h"] * height

        hits: list[tuple[float, float, float, float]] = []
        for (bx, by, bw, bh) in boxes:
            bx2, by2 = bx + bw, by + bh
            ix1, iy1 = max(bx, rx1), max(by, ry1)
            ix2, iy2 = min(bx2, rx2), min(by2, ry2)
            inter_w, inter_h = max(0.0, ix2 - ix1), max(0.0, iy2 - iy1)
            box_area = bw * bh
            if box_area > 0 and (inter_w * inter_h) / box_area >= overlap_threshold:
                hits.append((bx, by, bx2, by2))

        if hits:
            x1 = min(h[0] for h in hits)
            y1 = min(h[1] for h in hits)
            x2 = max(h[2] for h in hits)
            y2 = max(h[3] for h in hits)
            matched[field] = (x1, y1, x2 - x1, y2 - y1)
    return matched


def generation_kwargs(max_new_tokens: int) -> dict[str, Any]:
    """Decoder settings for one field crop.

    ``use_cache`` must be passed explicitly: microsoft/trocr-large-printed's
    own generation_config.json ships ``"use_cache": false``, so the decoder
    re-runs all 12 layers over the whole growing prefix at every step -
    measured 2.2x slower (103.9s -> 47.3s over 3 crops) for byte-identical
    decoded text. ``num_beams=1`` keeps it greedy; beam search multiplies CPU
    cost for no gain on short printed field values.
    """
    return {"max_new_tokens": max_new_tokens, "num_beams": 1, "use_cache": True}


def select_fields_for_recognition(
    matched_rois: dict[str, Box],
    fields: dict[str, dict],
    low_conf_floor: float,
) -> list[str]:
    """Which ROI-matched fields are worth spending TrOCR on, in priority order.

    Each crop costs real CPU seconds, so a field Tesseract already read at or
    above ``low_conf_floor`` is skipped. Keep that floor HIGH (see
    ``Settings.roi_tesseract_confidence_floor``): measured on a real BIR page,
    Tesseract reported 68-78% confidence on values it read WRONG
    ("NORTHZ2N STAR FINANCE", "GEMINI STREZT", "CONSTRUCTION CF"), so a low
    floor gates out precisely the fields TrOCR exists to fix - a 60 floor cost
    2 required fields and dropped the page's text-validation score from 1.0 to
    0.778. Tesseract confidence is weak evidence of correctness on these forms;
    the time budget, not this gate, is what makes the pass bounded.

    Required fields come first because ``score_quality()`` computes the
    text-validation score from required fields alone, so when the caller's
    time budget cuts the pass short the optional fields are what's lost.
    """
    required, optional = [], []
    for field in matched_rois:
        existing = fields.get(field)
        if existing is not None:
            confidence = existing.get("confidence")
            if existing.get("matched") and confidence is not None and confidence >= low_conf_floor:
                continue
        (required if (existing or {}).get("required", True) else optional).append(field)
    return required + optional


def recognize_crop(image, box: Box, processor: Any, model: Any, *,
                   pad: int = 4, max_new_tokens: int = 64) -> str:
    """Crop ``box`` out of ``image`` (numpy array) with a small pad, run TrOCR,
    return the decoded text (stripped, empty string if the crop is degenerate)."""
    import numpy as np
    import torch
    from PIL import Image

    height, width = image.shape[:2]
    x, y, w, h = box
    x0 = max(0, int(x) - pad)
    y0 = max(0, int(y) - pad)
    x1 = min(width, int(x + w) + pad)
    y1 = min(height, int(y + h) + pad)
    if x1 <= x0 or y1 <= y0:
        return ""

    crop = np.asarray(image)[y0:y1, x0:x1]
    pil_crop = Image.fromarray(crop).convert("RGB")

    pixel_values = processor(images=pil_crop, return_tensors="pt").pixel_values
    with torch.inference_mode():  # eval() alone still tracks autograd state
        generated_ids = model.generate(pixel_values, **generation_kwargs(max_new_tokens))
    text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]
    return text.strip()


def resolve_roi_config(
    roi_config: dict[str, Any], template: str, city: str | None = None,
) -> dict[str, dict[str, float]] | None:
    """``bir``/``dti`` map straight to their field dict. ``business_permit``
    is nested by city (today: Digos only) - ``city`` must already be known
    (e.g. from the label+regex pass's own ``city_issued`` extraction), since
    this module has no independent way to identify the issuing city."""
    if template == "business_permit":
        if not city:
            return None
        return roi_config.get("business_permit", {}).get(_normalize_city(city))
    return roi_config.get(template)


def _normalize_city(city: str) -> str:
    return re.sub(r"^city of\s+", "", city.strip(), flags=re.IGNORECASE).strip().lower()


def extract_fields_via_roi(
    image,
    template: str,
    roi_config: dict[str, Any],
    detector: Any,
    trocr: tuple[Any, Any] | None,
    *,
    city: str | None = None,
    field_specs: list[dict] | None = None,
    fields: dict[str, dict] | None = None,
    low_conf_floor: float = 60.0,
    budget_seconds: float | None = None,
    max_new_tokens: int = 64,
    clock: Callable[[], float] = time.monotonic,
) -> RoiOutcome:
    """Recognize the field values worth spending TrOCR on, within a time budget.

    Returns a {@see RoiOutcome} whose ``fields`` maps {field_key:
    recognized_value} for fields with a confident ROI match, omitting
    everything else so the caller's per-field merge falls back to the existing
    label+regex+positional result. Never raises - any failure here is
    equivalent to "no ROI match" for that field.

    ``fields`` (the label+regex pass's own result) drives the gate: fields
    Tesseract already read confidently are skipped entirely. ``budget_seconds``
    caps the whole pass; ``clock`` is injectable so the budget is testable
    without sleeping.
    """
    empty = RoiOutcome({}, _diagnostics([], [], [], 0.0))
    if detector is None or trocr is None:
        return empty

    tmpl_roi = resolve_roi_config(roi_config, template, city)
    if not tmpl_roi:
        return empty

    try:
        boxes = detect_boxes(image, detector)
    except Exception:
        return empty
    if not boxes:
        return empty

    height, width = image.shape[:2]
    matched = match_rois(boxes, tmpl_roi, (width, height))
    if not matched:
        return empty

    selected = select_fields_for_recognition(matched, fields or {}, low_conf_floor)

    processor, model = trocr
    specs_by_key = {spec["key"]: spec for spec in (field_specs or [])}
    results: dict[str, str] = {}
    recognized: list[str] = []
    over_budget: list[str] = []
    started = clock()

    for index, field in enumerate(selected):
        if budget_seconds is not None and clock() - started >= budget_seconds:
            over_budget = selected[index:]  # the rest keep their label+regex value
            break

        try:
            text = recognize_crop(image, matched[field], processor, model,
                                  max_new_tokens=max_new_tokens)
        except Exception:
            continue
        if not text:
            continue

        spec = specs_by_key.get(field)
        pattern = spec.get("regex") if spec else None
        if pattern:
            match = re.search(pattern, text, re.IGNORECASE)
            if not match:
                continue  # fails validation -> fall back to label+regex for this field
            text = match.group(1) if match.groups() else match.group(0)

        results[field] = text
        recognized.append(field)

    return RoiOutcome(
        results, _diagnostics(selected, recognized, over_budget, clock() - started)
    )


def _diagnostics(attempted: list[str], recognized: list[str],
                 over_budget: list[str], elapsed: float) -> dict[str, Any]:
    return {
        "attempted": attempted,
        "recognized": recognized,
        "skipped_over_budget": over_budget,
        "elapsed_s": round(elapsed, 2),
    }
